### ISSUE TITLE
changing some micro-synteny search parameters results in Track Search error

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/gcv-client#14] opened 2021-08-18 22:24 UTC
changing Min Matched Families or Max Insertion Size and submitting the change removes result tracks but indicates an error in the "pipeline" with "One or more searches failed" and "No status for <server>" for all servers. No errors that I can see in the javascript console, just a "verbose message" : 
"[Violation] 'submit' handler took 216ms"

**Comment by alancleary** [comment] 2021-12-14 22:32
Duplicate of #343. Closing.

**Closed by alancleary** 2021-12-14 22:32 UTC
Labels: bug
